name: Docker Image CI

on:
  push:
    branches:
      - fix-ci  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Build the Docker image
      run: docker build ./central-library --file Dockerfile --tag dopudjdejan/central-library:latest

    - name: Docker Push
      run: docker push dopudjdejan/central-library:latest
